### ISSUE TITLE
Damaged Payload

### ISSUE THREAD

**Issue by pcwizatl** [rapmd73/JackrabbitRelay#20] opened 2023-04-05 15:24 UTC
I am trying to work my way through the install on my VPS.  Everytime the alert goes off I keep seeing Damaged Payload.  The payload file looks correct.  Its happening every time my alter goes off.  The identity looks good as well.  Can you help point me in the right direction.

2023-04-05 14:17:38.237943 52.32.178.7      Damaged payload: Red circle WaveTrend Overbought

{
  "Time":"2023-04-05T14:00:00Z",
  "Recipe":"#Momentum #MoneyFlow #RSI",
  "Action":"sell",
  "Exchange":"kucoin",
  "Account":"MAIN",
  "Market":"Spot",
  "Asset":"DPXUSDT",
  "Price":"255.825",
  "AvgProfit":"0",
  "LProfit":"-95",
  "TCycles":"-99",
  "CBuys":"60.25034550708317",
  "MBCycle":"72.55855852226505",
  "TBuys":"-12.308213015181877",

**Comment by rapmd73** [comment] 2023-04-05 15:44
Hi,

Thank you for using Jackrabbit Relay.

Based upon what you provided for email, you are missing the final curly brace  **}** and have a comma on the last item.

JSON can be a difficult format to work with in the beginning, but once you get used to its idiosyncrasies, it does get easier.

The best approach is to run your full and complete alert message or payload through a JSON validator. The link below is for a free one that does exceptionally well that I use constantly.

[JSON validator](https://jsonformatter.curiousconcept.com/)

Please be aware that in order to really be able to evaluate your payload, I will need to see the entire payload with your identity sanitized. 

Thank you.

**Comment by pcwizatl** [comment] 2023-04-05 16:46
This is pretty much my exact payload file minus all the zeros in between.  I went to the JSON validator and keep getting an error around the Identity line.  Everything else looks good except for that section.


{
  "Time":"{{time}}",
  "Recipe":"#Momentum #RSI #MoneyFlow",
  "Action":"buy",
  "Exchange":"kucoin",
  "Account":"MAIN",
  "Market":"Spot",
  "Asset":"{{ticker}}",
  "Price":"{{close}}",
  "AvgProfit":"{{plot_0}}",
  "LProfit":"{{plot_1}}",
  "TCycles":"{{plot_2}}",
  "CBuys":"{{plot_3}}",
  "MBCycle":"{{plot_4}}",
  "TBuys":"{{plot_5}}",
  "Link":"https://www.tradingview.com/chart/bB4Qf4at",
  "Identity":")Cd%l!;K;&o[ebVvj)=>5S<:.;#}z@0[gos9jMT:F_foIBj>_vKHW,8QSp#2O*=xUk9k~:kXliX5td1W4rEhV3w!/2QmdTbW(h8
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
)_}+*=M4,f:e<]3+OLtzOvkfsvyFk%2g:,dkQIA{1)!H6Ey(R.~SaMS%&I~haC!1j5fu:4uDLCi#N.flVjEO>d",
}

**Comment by rapmd73** [comment] 2023-04-05 18:08
I edited your identity out. Please make sure to never ever release it, even a portion of it could put your system at risk.

The last, after identity should not be there and that is why you are getting a validation error.

Please remove the final, before the last bracket and it should validate and work properly.

Thank you.

**Comment by pcwizatl** [comment] 2023-04-05 19:34
Thank You appreciate you helping.  When I put in the Identity and ran in through the validator, its still coming back as "invalid character at position 101 and it highlights the entire identity section.  I checked both payloads for the Buy and Sell and neither of them have the comma after identity.

**Comment by rapmd73** [comment] 2023-04-05 22:40
I received your message email, not sure why its not here...

I've tried to reproduce the issue and haven't so far.

Please save the current identity file to a different name and regenerate the identity, follingg the guide:

https://github.com/rapmd73/JackrabbitRelay/wiki/Identity

The JSON validator not pass a validation fests that a quote **"** mark is embedded in the identity string. A comma won't affect anthing as long as the identity string follows the proper JSON format.

Please test your JSON payload withouy the actual identity string, ie:

**"Identity":"testString"**

I've marked this as a bug until I can fully verify that a quote is not being generated in the identity string.

Something you can try is to copy the Identity.cfg into the validator and see if it validates by itself. It should unless the copy/paste process is damaging the copy buffer.

Please let me know the results of these tests.

**Comment by rapmd73** [comment] 2023-04-05 23:24
Also try this:

Save your JSON payload to a file on your VPS. then run this command:

python3 -m json.tool < file

**file** will be the name of the file you created. Any errors will be explicitly identified by column and position. its not the friendliest way, but it is direct and to the point.

Thank you.

**Comment by pcwizatl** [comment] 2023-04-06 12:35
Thanks for the update.  I went line by line in with the file and thought everything was good to go.  I will try your suggestions above and circle back to let you know if I have success.

Thanks

**Comment by pcwizatl** [comment] 2023-04-07 00:04
> I received your message email, not sure why its not here...
> 
> I've tried to reproduce the issue and haven't so far.
> 
> Please save the current identity file to a different name and regenerate the identity, following the guide:
> 
> https://github.com/rapmd73/JackrabbitRelay/wiki/Identity
> 
> The JSON validator not pass a validation tests if a quote **"** mark is embedded in the identity string. A comma won't affect anthing as long as the identity string follows the proper JSON format.
> 
> Please test your JSON payload withouy the actual identity string, ie:
> 
> **"Identity":"testString"**
> 
> I've marked this as a bug until I can fully verify that a quote is not being generated in the identity string.
> 
> Something you can try is to copy the Identity.cfg into the validator and see if it validates by itself. It should unless the copy/paste process is damaging the copy buffer.
> 
> Please let me know the results of these tests.

When testing the JSON

**Comment by pcwizatl** [comment] 2023-04-07 00:07
I regenerated the Identity file and ran it through the JSON Validator and it passed.  I placed the new identity in the JSON validator checked it and it passed.  When the alert triggered I still received the Damaged Payload message in the JackrabbitRelay log file.  Everything looks to be setup and configured correctly but something isnt working.  Sorry for the back and fourth but im just trying to get up and running.


Thanks

**Comment by rapmd73** [comment] 2023-04-07 13:29
No apologies needed. This needs to be figured out why it is not working properly, when I agree with you that it should be.

At this point, the only thing that I can think of is somehow during the copy and paste the process of your payload to your trading view alert, that's something is not being pasted properly in the alert window.

If this continues, it might be worth considering moving to a private conversation where we can discuss the possibility of a team viewer session to determine exactly what is going on and correcting the problem so that it works properly.

At this point though, please save your complete payload to a file on your VPS and follow the directions in the wiki force feeding the payload into Relay itself. We need to eliminate any possibilities of a bug within the system itself and force feeding the payload into the various processors would help determine that.

I am also conducting various tests on my side to see if I can reproduce any of the situation and or maybe come up with an approach to break the system that would reveal where this problem is.

**Comment by rapmd73** [comment] 2023-04-07 18:59
This is experimental, but please try it anyway:

https://rapmd.net/Validator.shtml

Copy and paste youe entire payload here and click submit. It will analyze the payload and try to find any problems and identify them. So far, in testing it, it has detected all the errors I've given it.

Thank you.

**Comment by pcwizatl** [comment] 2023-04-07 19:47
Ok, I was just about to message you.  After the forced payload testing these are my results.  Yes I can do a Zoom session we should need to do that to get me on my way.

/home/JackrabbitRelay2/Base# /home/JackrabbitRelay2/Base/PlaceOrder.tester < /home/Jackrabb
itRelay2/Testing/msgSell
2023-04-07 19:32:04.612213    8671 PlaceOrder Tester 0.0.0.1.50
2023-04-07 19:32:04.612515    8671 Order parsed
2023-04-07 19:32:04.612600    8671 |- Time: {{time}}
2023-04-07 19:32:04.612679    8671 |- Recipe: #Momentum#RSI#MoneyFlow
2023-04-07 19:32:04.612748    8671 |- Action: sell
2023-04-07 19:32:04.612807    8671 |- Exchange: kucoin
2023-04-07 19:32:04.612860    8671 |- Account: MAIN
2023-04-07 19:32:04.612909    8671 |- Market: spot
2023-04-07 19:32:04.612957    8671 |- Asset: {{TICKER}}
2023-04-07 19:32:04.613007    8671 |- Price: {{close}}
2023-04-07 19:32:04.613057    8671 |- AvgProfit: {{plot_0}}
2023-04-07 19:32:04.613107    8671 |- LProfit: {{plot_1}}
2023-04-07 19:32:04.613157    8671 |- TCycles: {{plot_2}}
2023-04-07 19:32:04.613206    8671 |- CBuys: {{plot_3}}
2023-04-07 19:32:04.613255    8671 |- MBCycle: {{plot_4}}
2023-04-07 19:32:04.613304    8671 |- TBuys: {{plot_5}}
2023-04-07 19:32:04.613353    8671 |- Link: https://www.tradingview.com/chart/bB4Qf4at
2023-04-07 19:32:04.613404    8671 |- OrderType: market
2023-04-07 19:32:04.613464    8671 Processing Completed: 0:00:01.196484 seconds

/home/JackrabbitRelay2/Base# /home/JackrabbitRelay2/Base/PlaceOrder.dsr < /home/JackrabbitR
elay2/Testing/msgSell
2023-04-07 19:39:17.913632    8703 PlaceOrder DSR 0.0.0.1.50
2023-04-07 19:39:17.913913    8703 Order parsed
2023-04-07 19:39:17.913993    8703 |- Time: {{time}}
2023-04-07 19:39:17.914067    8703 |- Recipe: #Momentum#RSI#MoneyFlow
2023-04-07 19:39:17.914133    8703 |- Action: sell
2023-04-07 19:39:17.914247    8703 |- Exchange: kucoin
2023-04-07 19:39:17.914347    8703 |- Account: MAIN
2023-04-07 19:39:17.914416    8703 |- Market: spot
2023-04-07 19:39:17.914475    8703 |- Asset: {{TICKER}}
2023-04-07 19:39:17.914530    8703 |- Price: {{close}}
2023-04-07 19:39:17.914588    8703 |- AvgProfit: {{plot_0}}
2023-04-07 19:39:17.914646    8703 |- LProfit: {{plot_1}}
2023-04-07 19:39:17.914710    8703 |- TCycles: {{plot_2}}
2023-04-07 19:39:17.914764    8703 |- CBuys: {{plot_3}}
2023-04-07 19:39:17.914826    8703 |- MBCycle: {{plot_4}}
2023-04-07 19:39:17.914877    8703 |- TBuys: {{plot_5}}
2023-04-07 19:39:17.914953    8703 |- Link: https://www.tradingview.com/chart/bB4Qf4at
2023-04-07 19:39:17.915067    8703 |- OrderType: market
Traceback (most recent call last):
  File "/home/JackrabbitRelay2/Base/PlaceOrder.dsr", line 86, in <<module>
    main()
  File "/home/JackrabbitRelay2/Base/PlaceOrder.dsr", line 57, in main
    fn=relay.DataDirectory+'/'+relay.GetExchangeLast()+'.'+relay.GetAccountLast()+'.'+relay.Order['Asset']+'.DSR'
TypeError: can only concatenate str (not "NoneType") to str



Thanks

**Comment by pcwizatl** [comment] 2023-04-07 19:52
I used the link with my entire Payload including the identity.  I sent a second time because I missed the very first line which it currently has no # to comment it out.  Just a thought on if thats my issue.



Thanks

**Comment by rapmd73** [comment] 2023-04-07 22:00
> /home/JackrabbitRelay2/B+ase# /home/JackrabbitRelay2/Base/PlaceOrder.dsr < /home/JackrabbitR elay2/Testing/msgSell 
> 2023-04-07 19:39:17.913632 8703 PlaceOrder DSR 0.0.0.1.50 
> 2023-04-07 19:39:17.913913 8703 Order parsed 
> 2023-04-07 19:39:17.913993 8703 |- Time: {{time}} 
> 2023-04-07 19:39:17.914067 8703 |- Recipe: #Momentum#RSI#MoneyFlow 
> 2023-04-07 19:39:17.914133 8703 |- Action: sell 
> 2023-04-07 19:39:17.914247 8703 |- Exchange: kucoin 
> 2023-04-07 19:39:17.914347 8703 |- Account: MAIN 
> 2023-04-07 19:39:17.914416 8703 |- Market: spot 
> 2023-04-07 19:39:17.914475 8703 |- Asset: {{TICKER}} 
> 2023-04-07 19:39:17.914530 8703 |- Price: {{close}} 
> 2023-04-07 19:39:17.914588 8703 |- AvgProfit: {{plot_0}} 
> 2023-04-07 19:39:17.914646 8703 |- LProfit: {{plot_1}} 
> 2023-04-07 19:39:17.914710 8703 |- TCycles: {{plot_2}} 
> 2023-04-07 19:39:17.914764 8703 |- CBuys: {{plot_3}} 
> 2023-04-07 19:39:17.914826 8703 |- MBCycle: {{plot_4}} 
> 2023-04-07 19:39:17.914877 8703 |- TBuys: {{plot_5}} 
> 2023-04-07 19:39:17.914953 8703 |- Link: https://www.tradingview.com/chart/bB4Qf4at 
> 2023-04-07 19:39:17.915067 8703 |- OrderType: market Traceback (most recent call last): File "/home/JackrabbitRelay2/Base/PlaceOrder.dsr", line 86, in < main() File "/home/JackrabbitRelay2/Base/PlaceOrder.dsr", line 57, in main fn=relay.DataDirectory+'/'+relay.GetExchangeLast()+'.'+relay.GetAccountLast()+'.'+relay.Order['Asset']+'.DSR' TypeError: can only concatenate str (not "NoneType") to str

This error is normar because the DSR is expecting numbers, not TradingView macros, ie **{{plot_0}}**

**Comment by pcwizatl** [comment] 2023-04-08 10:52
Ok, after testing I think i've figured out that I had something incorrect in the payload. I am no longer receiving errors and generating some additional logs.  I will move some small amount of udst to Kucoin to begin testing live.

Thanks

**Comment by rapmd73** [comment] 2023-04-08 14:06
That sounds good.

I recomend running the tester for a few days to collect log data to ensure full functionality before risking real money.  When you do start to trade in a live market, please start with something like TRX or smaller where you can buy/sell very small amounts.

I will leave this ticket open for a few days.

Thank you.

**Comment by pcwizatl** [comment] 2023-04-09 12:48
Can I ask if you would know what this might be related to.  I'm seeing this in the log file and there is definitely funds in the Main and Spot account on Kucoin.  Or if there is something that I am missing that talks about this in a link please point me in the right direction.

create_order failed with: kucoin The order funds should be more than 0.1 USDT.

**Comment by rapmd73** [comment] 2023-04-09 14:22
The coin pair you are trading is below the minimum the Kucoin requires for this pair (0.1 USDT). Relay is usually capable of figuring out the minimum properly, but there are times when the exchange doesn't report the proper minimum. 

If you are not using Base or USD in your order payload, the easiest fix is to add,

**"Quote":"0.11",**

You want to be a tiny bit over the minimum to account for slippage. This is trial and error though, especially in fast moving markets. This translate to 0.11 USDT. This is a normal response that can occur when you are pushing the lowest an exchange will support.

If you are using Base or USD, you can simple calculate the equivalent or change to Quote. Please note that if you rty to use Base or USD and Quote in the same order payload, Relay will give an error and not process the order.

Thank you.

**Comment by rapmd73** [comment] 2023-04-09 14:23
I'm closing this ticket as the issue seems to be fixed. If the problem occurs again, please let me know.

Thank you.

**Closed by rapmd73** 2023-04-09 14:23 UTC
Labels: bug
